# Generated by Django 5.2.3 on 2025-09-28 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("manufacturer", models.CharField(max_length=80)),
                ("model_number", models.CharField(max_length=40)),
                ("serial_number", models.CharField(db_index=True, max_length=40)),
                ("udi_carrier", models.CharField(blank=True, max_length=200)),
                ("firmware", models.CharField(blank=True, max_length=40)),
                ("device_type", models.CharField(max_length=120)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "device",
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "loinc_code",
                    models.CharField(
                        help_text="LOINC code for the metric", max_length=20
                    ),
                ),
                (
                    "metric_display_name",
                    models.CharField(
                        blank=True,
                        help_text="Display of the metric",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vital-signs", "Vital signs"),
                            ("laboratory", "Laboratory"),
                            ("survey", "Survey"),
                            ("procedure", "Procedure"),
                            ("imaging", "Imaging"),
                            ("exam", "Exam"),
                            ("therapy", "Therapy"),
                            ("activity", "Activity"),
                            ("social-history", "Social history"),
                        ],
                        help_text="Category of the metric",
                        max_length=255,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(help_text="Unit of the metric", max_length=20),
                ),
                (
                    "effective_timestamp",
                    models.DateTimeField(
                        help_text="timestamp of when the observation was made"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the device that made the observation",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("final", "Final"),
                            ("amended", "Amended"),
                            ("entered-in-error", "Entered in Error"),
                            ("preliminary", "Preliminary"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "observation",
            },
        ),
    ]
