# Generated by Django 5.2.3 on 2025-06-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
        migrations.AlterModelTable(
            name='observation',
            table='observation',
        ),
    ]
