# Generated by Django 5.2.3 on 2025-08-17 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0002_alter_device_table_alter_observation_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="id",
            new_name="record_id",
        ),
        migrations.RenameField(
            model_name="observation",
            old_name="id",
            new_name="record_id",
        ),
    ]
