# Generated by Django 5.2.3 on 2025-09-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("observations", "0003_rename_id_device_record_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="observation",
            name="metric_code",
        ),
        migrations.RemoveField(
            model_name="observation",
            name="raw_fhir_json",
        ),
        migrations.AddField(
            model_name="observation",
            name="category",
            field=models.CharField(
                choices=[
                    ("vital-signs", "Vital signs"),
                    ("laboratory", "Laboratory"),
                    ("survey", "Survey"),
                    ("procedure", "Procedure"),
                    ("imaging", "Imaging"),
                    ("exam", "Exam"),
                    ("therapy", "Therapy"),
                    ("activity", "Activity"),
                    ("social-history", "Social history"),
                ],
                default="laboratory",
                help_text="Category of the metric",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="observation",
            name="loinc_code",
            field=models.CharField(
                default=0, help_text="LOINC code for the metric", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="observation",
            name="metric_display_name",
            field=models.CharField(
                blank=True, help_text="Display of the metric", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="observation",
            name="status",
            field=models.CharField(
                choices=[
                    ("final", "Final"),
                    ("amended", "Amended"),
                    ("entered-in-error", "Entered in Error"),
                    ("preliminary", "Preliminary"),
                    ("cancelled", "Cancelled"),
                ],
                default="final",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="observation",
            name="device_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the device that made the observation",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="effective_timestamp",
            field=models.DateTimeField(
                help_text="timestamp of when the observation was made"
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="unit",
            field=models.CharField(help_text="Unit of the metric", max_length=20),
        ),
    ]
