# Generated by Django 5.2.3 on 2025-09-28 06:42

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("organizations", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareTeamMembership",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="The role of the member in the care team, corresponds to CareTeam.participant.role",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 9, 28, 6, 42, 19, 448978, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "reason_for_assignment",
                    models.TextField(
                        blank=True,
                        help_text="Why the care team exists for this patient",
                        null=True,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "clinician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_team_memberships",
                        to="accounts.clinicianprofile",
                    ),
                ),
                (
                    "managing_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_team_memberships",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "care_team_membership",
                "unique_together": {("patient", "clinician", "managing_organization")},
            },
        ),
    ]
