# Generated by Django 5.2.3 on 2025-10-05 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careteammemberships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careteammembership",
            name="assigned_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 5, 7, 6, 57, 527117, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
