# Generated by Django 5.2.3 on 2025-08-17 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careteammemberships", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="careteammembership",
            old_name="id",
            new_name="record_id",
        ),
        migrations.AddField(
            model_name="careteammembership",
            name="managing_organization",
            field=models.ForeignKey(
                default="7d74f8fd-aa7a-4084-a3d4-c0a1e4d1033a",
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="careteammembership",
            name="reason_for_assignment",
            field=models.TextField(
                blank=True,
                help_text="Why the care team exists for this patient",
                null=True,
            ),
        ),
    ]
