# Generated by Django 5.2.3 on 2025-09-19 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careteammemberships", "0002_rename_id_careteammembership_record_id_and_more"),
        ("patients", "0004_rename_id_patient_record_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="careteammembership",
            name="clinician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_team_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="careteammembership",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_team_memberships",
                to="patients.patient",
            ),
        ),
        migrations.AlterField(
            model_name="careteammembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                ],
                max_length=255,
            ),
        ),
    ]
