# Generated by Django 5.2.3 on 2025-10-05 07:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientorganizationconsent",
            name="consented_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 10, 5, 7, 6, 57, 526741, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="patientorganizationconsent",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2026, 10, 5, 7, 6, 57, 526752, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="patientorganizationconsent",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_organization_consents",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="patientorganizationconsent",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_organization_consents",
                to="patients.patient",
            ),
        ),
    ]
