# Generated by Django 5.2.3 on 2025-08-23 21:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClinicianInvitation",
            new_name="OrganizationInvitation",
        ),
        migrations.AlterModelTable(
            name="organizationinvitation",
            table="organization_invitation",
        ),
    ]
