# Generated by Django 5.2.3 on 2025-08-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0002_rename_clinicianinvitation_organizationinvitation_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationinvitation",
            old_name="clinician_email",
            new_name="invitee_email",
        ),
    ]
