# Generated by Django 5.2.3 on 2025-09-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0003_rename_clinician_email_organizationinvitation_invitee_email",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="raw_fhir_json",
        ),
    ]
