# Generated by Django 5.2.3 on 2025-09-21 05:18

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_remove_organization_raw_fhir_json"),
        ("patients", "0004_rename_id_patient_record_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientOrganizationConsent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consented_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2025, 9, 21, 5, 18, 51, 730372, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2026, 9, 21, 5, 18, 51, 730385, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("is_revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "patient_organization_consent",
                "unique_together": {("patient", "organization")},
            },
        ),
    ]
