# Generated by Django 5.2.3 on 2025-09-28 07:06

from django.db import migrations


def create_initial_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="Admin")
    Group.objects.create(name="Clinician")
    Group.objects.create(name="Patient")

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_groups),
    ]
