# Generated by Django 5.2.3 on 2025-06-29 07:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rpmuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='rpmuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='rpmuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='rpmuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='rpmuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='rpmuser',
            name='username',
        ),
        migrations.AddField(
            model_name='rpmuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('clinician', 'Clinician'), ('patient', 'Patient')], default='patient', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rpmuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='rpmuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rpmuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rpmuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='rpmuser',
            table='account_user',
        ),
    ]
