# Generated by Django 5.2.3 on 2025-08-08 05:43

from django.db import migrations


class Migration(migrations.Migration):
    def create_groups(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Group.objects.create(name='Clinician')
        Group.objects.create(name='Patient')

    dependencies = [
        ('accounts', '0003_loginattempt'),
    ]

    operations = [migrations.RunPython(create_groups, migrations.RunPython.noop)]