# Generated by Django 5.2.3 on 2025-08-10 04:08

from django.db import migrations


class Migration(migrations.Migration):
    def create_organization_admin_group(apps, schema_editor):
        Group = apps.get_model('auth', 'Group')
        Group.objects.create(name='Organization Admin')

    dependencies = [
        ("accounts", "0004_create_groups"),
    ]

    operations = [migrations.RunPython(create_organization_admin_group, migrations.RunPython.noop)]
