# Generated by Django 5.2.3 on 2025-08-17 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_create_organization_admin_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loginattempt",
            old_name="id",
            new_name="record_id",
        ),
        migrations.RenameField(
            model_name="rpmuser",
            old_name="id",
            new_name="record_id",
        ),
        migrations.CreateModel(
            name="ClinicianProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "record_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "npi_number",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("medical_license_number", models.CharField(max_length=255)),
                ("license_state", models.CharField(max_length=255)),
                ("license_expiration_date", models.DateField()),
                ("specialty", models.CharField(max_length=255)),
                ("credentials_verified", models.BooleanField(default=False)),
                ("verification_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinician_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_clinician_profiles",
                        related_query_name="verified_clinician_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clinician_profile",
            },
        ),
    ]
