# Generated by Django 5.2.3 on 2025-08-31 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_rename_id_loginattempt_record_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicianprofile",
            name="verification_date",
        ),
        migrations.AddField(
            model_name="clinicianprofile",
            name="verification_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
