# Generated by Django 5.2.3 on 2025-06-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='careteammembership',
            name='role',
            field=models.CharField(help_text='The role of the member in the care team, corresponds to CareTeam.participant.role', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='patientidentifier',
            unique_together={('system', 'value')},
        ),
        migrations.AlterModelTable(
            name='careteammembership',
            table='care_team_membership',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
        migrations.AlterModelTable(
            name='patientidentifier',
            table='patient_identifier',
        ),
    ]
