# Generated by Django 5.2.3 on 2025-08-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_sex_patient_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareTeamMembership',
        ),
    ]
