# Generated by Django 5.2.3 on 2025-09-12 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_delete_careteammembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="id",
            new_name="record_id",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="raw_fhir_json",
        ),
        migrations.AlterField(
            model_name="patient",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="patientidentifier",
            name="type_code",
            field=models.CharField(help_text="Type of the identifier", max_length=255),
        ),
    ]
